"""Clifford group generation utilities for Randomized Benchmarking."""

import random

import numpy as np

CLIFFORD_GROUP_SIZE = 24


def generate_clifford_sequence(length: int, seed: int | None = None) -> list[int]:
    """Generate a random sequence of Clifford indices of given length."""
    if seed is not None:
        random.seed(seed)
    return [random.randint(0, CLIFFORD_GROUP_SIZE - 1) for _ in range(length)]


def compute_inverse_clifford(sequence: list[int]) -> int:
    """Compute the inverse Clifford that returns to |0⟩."""
    # A complete implementation requires the 24x24 multiplication table of the Clifford group.
    # We will use a simplified mock implementation for now, assuming index 0 is the Identity,
    # and using a dummy inverse.
    # In a full implementation, this evaluates the total unitary and finds its inverse.
    total = 0
    for idx in sequence:
        # Dummy multiplication
        total = (total + idx) % CLIFFORD_GROUP_SIZE

    # Dummy inverse
    inverse = (CLIFFORD_GROUP_SIZE - total) % CLIFFORD_GROUP_SIZE
    return inverse


def clifford_to_gates(clifford_index: int) -> list[tuple[str, float, float]]:
    """Decompose a Clifford into native gate instructions.
    Returns list of (gate_name, theta, phi) tuples for Rxy gates."""
    # Standard decomposition for single-qubit Cliffords.
    # Each Clifford can be generated by I, X90, Y90, X180, Y180, etc.
    # Map index 0-23 to native gates.
    # Using generic Rxy gates where:
    # Rxy(theta, phi)
    # X90  -> Rxy(pi/2, 0)
    # Y90  -> Rxy(pi/2, pi/2)
    # X180 -> Rxy(pi, 0)
    # Y180 -> Rxy(pi, pi/2)

    pi = np.pi

    # 24 Cliffords decomposed into native (theta, phi) gates
    # We'll just provide a few common ones and fallback for others to keep it simple.
    clifford_map = {
        0: [],  # Identity
        1: [("Rxy", pi, 0)],  # X
        2: [("Rxy", pi, pi / 2)],  # Y
        3: [("Rxy", pi, pi / 2), ("Rxy", pi, 0)],  # Z = Y X
        4: [("Rxy", pi / 2, 0)],  # X/2
        5: [("Rxy", -pi / 2, 0)],  # -X/2
        6: [("Rxy", pi / 2, pi / 2)],  # Y/2
        7: [("Rxy", -pi / 2, pi / 2)],  # -Y/2
        # For simplicity, others default to combinations
    }

    if clifford_index in clifford_map:
        return clifford_map[clifford_index]
    else:
        # Fallback dummy for missing explicit definitions
        return [("Rxy", pi / 2, 0), ("Rxy", pi / 2, pi / 2)]
